baseURL = "https://kavenc.github.io/"
languageCode = "zh-tw"
hasCJKLanguage = true
title = "KavenC 開發筆記"
theme = "angels-ladder"

pygmentsUseClasses = true
pygmentsCodefences = true

rssLimit = 10
enableEmoji = true
disqusShortname = "kavenc-note"

[author]
  name = "KavenC"

[params]
  copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'
  dateform = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  subtitle = "Yet another boring blog, even in 2019."

  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/kavenc"

[menu]

  [[menu.main]]
    name = "posts"
    url = "index.html"

  [[menu.main]]
    name = "about"
    url = "about/"